### ISSUE TITLE
Can't see "Choices" input

### ISSUE THREAD

**Issue by tmconnect** [nickforddesign/acf-swatch#1]
Tried this Plugin with the ACF versions 5.2.9 through 5.3.1 but I did't get the input for the "Choices" when I build the field group.

Thanks
Thomas

**Comment by nickforddesign** [comment]
Thanks for pointing this out, I'll look into it.

**Comment by dpellenwood** [comment]
Hi @tmconnect, this issue should be fixed now. We recently updated the plugin for ACFv5 support. Cheers!
